#!/usr/bin/bash

IMAGE_IDS=($(sudo docker images --filter label=role=big-catalog-cli -q))
if [[ ${#IMAGE_IDS[@]} > 1 ]]; then
  unset IMAGE_IDS[0]
  docker rmi -f ${IMAGE_IDS[@]}
fi
#echo "Getting big catalog container id"
IMAGE_ID=($(sudo docker images --filter label=role=big-catalog-cli -q))

#echo "Running docker image"
docker run --rm -ti -v ~/.big_catalog:/bc/.big_catalog -v /tmp:/bc_files "$IMAGE_ID" $@
flag=0
for i in $@; do
  if [[ $i == "-f" ]]; then
    flag=1
  elif [[ $flag -eq 1 ]]; then
    path_to=$i
    break
  fi
done
if [[ $flag -eq 1 ]]; then
#  echo "Moving created files to provided dir"
  root="${path_to::1}"
  if [[ $root != "/" ]]; then
    tmp_path="/tmp/$path_to*"
    path_to="$(pwd)/$path_to"
  else
    tmp_path="/tmp$path_to*"
  fi
  cp $tmp_path "${path_to%/*}/"
fi
