#!/usr/bin/bash

role="vast-db-cli"
IMAGE_ID=$(sudo docker images --filter "label=role=$role" --format "{{.ID}} {{.Tag}} {{.CreatedAt}}" |
           sort -k 3 -r | head -n 1 | awk '{print $1}')

docker run --rm -ti -v ~/.vast_db:/vast_db/.vast_db -v /tmp:/vast_db_cli_files "$IMAGE_ID" "$@"
flag=0
for i in "$@"; do
    if [[ $i == "-f" ]]; then
        flag=1
    elif [[ $flag -eq 1 ]]; then
        path_to=$i
        break
    fi
done

if [[ $flag -eq 1 ]]; then
    root="${path_to::1}"
    if [[ $root != "/" ]]; then
        tmp_path="/tmp/$path_to*"
        path_to="$(pwd)/$path_to"
    else
        tmp_path="/tmp$path_to*"
    fi

    cp "$tmp_path" "${path_to%/*}/"
fi
